### ISSUE TITLE
Crashes when enabled on Android/Mobile App

### ISSUE THREAD

**Issue by luccord** [SalokinGreen/NAI4Obsidian#2]
The plugin works beautifully on desktop, however it doesn't work at all on my Android. On current public version for both (Android - 1.4.9 and Desktop - 1.4.5), and tested on my main vault and on a new vault.

If installing on Android, it crashes as it seems to finish. When relaunching, Obsidian works fine but the plugin is disabled and does not re-enable. It gives me "Failed to load plugin nai4obsidian".

If the plugin is already installed on desktop then transferred onto my Android, Obsidian crashes at "Loading plugins..." The only way to open the vault is to disable the plugin on desktop or delete the plugin folder.

My guess is that the mobile version is based on an older version of desktop Obsidian ([v1.3.7 according to this post](https://obsidian.md/changelog/2023-08-31-mobile-v1.4.8/)) so the plugin might be calling a new function that isn't in this older version, but I'm the furthest thing from a developer so who knows. If you need any additional info, I'd be happy to help!

**Comment by SalokinGreen** [comment]
Hey there, thank you for your detailed message! Sorry for the long reply - I have been afk due to health reasons.

I'm going to look into how to make N4O mobile friendly. I'm aware of it not working on mobile.

**Comment by luccord** [comment]
Obsidian for mobile got a new update recently, which "includes all new functionality and bug fixes up to Obsidian Desktop v1.4.16". I tried out the plugin after updating and it works just fine now.
