### ISSUE TITLE
New plugin name requirements

### ISSUE THREAD

**Issue by joethei** [SalokinGreen/NAI4Obsidian#3]
Hi @SalokinGreen

Per our [developer policies](https://docs.obsidian.md/Developer+policies),
please ensure that your plugin's name does not include the word "Obsidian".
In addition, the plugin name should not include the word "Plugin", as that is unecessary duplication.
We have already modified the name of your plugin to "NovelAI" in our records.

To maintain compliance, take the following actions:

1. Modify the manifest.json file in your plugin repository.
2. Generate a new release for your plugin to ensure users download the updated manifest.

If you have a idea for a different plugin name, you may also submit a pull request to the [obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases) repository.

Thank you for your cooperation.
— the Obsidian team

**Comment by SalokinGreen** [comment]
Hello, I'm sorry for the late reply. I missed this. "NovelAI" sounds good, honestly. I'm going to change the manifest.json now :) Thank you for your help!

**Comment by joethei** [comment]
@SalokinGreen The version number in the manifest should be "1.2.0" not "1.2"

**Comment by SalokinGreen** [comment]
Hey, I don't have access to my pc until tomorrow morning. Going to change it as fast as possible. Could this be the reason why installing the plugin fails? @joethei

**Comment by joethei** [comment]
Yes, that is the reason.

**Comment by SalokinGreen** [comment]
@joethei Thank you for your help! I changed the version number and installing works now. :)
