### ISSUE TITLE
Error: Failed to install NovelAI

### ISSUE THREAD

**Issue by spaceoutlaws** [SalokinGreen/NAI4Obsidian#4]
Hi there!

I'm getting an error in Obsidian when trying to update the NovelAI plugin that just says, "Failed to install plugin NovelAI." Are there any troubleshooting steps for this kind of error? I haven't changed any of my settings in months.

Thank you!

**Comment by SalokinGreen** [comment]
Hey there, @varlineau
I'm going to look into this when I'm back on my pc, tomorrow. I just tried to install it on my phone and I got the error, too. Weird since the code worked on my pc.

**Comment by spaceoutlaws** [comment]
Thanks so much @SalokinGreen! I really appreciate it.

**Comment by SalokinGreen** [comment]
Hey, I found the problem. I will get to my pc tonight and fix it. Should be fixed in 1-2 hours :)

**Comment by SalokinGreen** [comment]
@varlineau Fixed it! Should work now. :)

**Comment by spaceoutlaws** [comment]
@SalokinGreen Verifying it works! Thank you!
